### ISSUE TITLE
Nginx looking for app.php in wrong place

### ISSUE THREAD

**Issue by ihaltsou** [dockerwest/nginx-pimcore#1]
Hello, 

Thank you for your great Nginx container for Pimcore. But I've a trouble with installation of Pimcore. 
After I've downloaded official package and unpacked it I can see that entry point is _**web/app.php**_ but the config of Nginx looking for _**index.php**_. 

Could you please explain what's wrong with my configuration? Thank you.

**Comment by BlackIkeEagle** [comment]
@ihaltsou from what you are saying you are using pimcore 5, the configuration is changed and the images can be found in https://github.com/dockerwest/nginx-pimcore5 / https://hub.docker.com/r/dockerwest/nginx-pimcore5/

If you are using it in combination with https://github.com/dockerwest/compose-pimcore then you should use the "pimcore5" branch there

**Comment by ihaltsou** [comment]
Thank you so much for the clarification. It was the point.
